# Quaderni Alfonsinesi N. 16</br>Novembre 2002#
##500 ANNI DELLA CHIESA</br>di S. Maria delle Grazie in Alfonsine##

![][copertina]

[copertina]: copertina.png "Acquarello originale eseguito dal Prof. Romeo Zanzi" height=870px width=600px

##INDICE

1. [Introduzione][] di Angelo Antonellini
2. [Prefazione][] di Adis Pasi
3. [Cronotassi dei vescovi di Faenza][]
4. [Cronotassi dei Rettori (Parroci), economi spirituali e arcipreti di S. Maria delle Grazie in Alfonsine][]
5. [Dove Romagna s'inabissa e perde][] di Adis Pasi
6. [Diario di guerra][] di Don Luigi Liverani
7. [Due vite umili - Il dotto Vescovo e il candido frate. Ricordo di Mons. Gardini vescovo di Bertinoro][] di Lorenzo Bedeschi
9. [Nostra gente. Padre Alfonso da Alfonsine][] di Luciano De Nardis
10. [... E io ti sparo contro un sonetto][] di Adis Pasi
11. [Canti popolari religiosi in Romagna][] di Giuseppe Bellosi


Un numero "speciale" dei Quaderni che vuole celebrare i Cinquecento anni della Comunità delle Alfonsine.
Cinque secoli fa (1502) la posa della prima pietra per la costruzione di una Chiesa in località Destra Senio.
Gli storici hanno identificato questo momento con la nascita ufficiale della nostra città. Documenti rari, preziosi per la loro autenticità, di avvenimenti storici (Francesi in Romagna) e di testimonianze, sofferte e qualificate, come il Diario di guerra di don Liverani. Esperienze e testimonianze che fissano le immagini di un viaggio attraverso il tempo e ricordano vicende umane per dare una identità socioculturale alla nostra comunità.
Una Chiesa che rappresentò il coagulo di un territorio abitato che stava sviluppandosi lungo il fiume Senio fra le acque malsane delle Valli, in situazioni ambientali difficili, condizionate da miseria ed epidemie devastanti.
L'Amministrazione Comunale è profondamente riconoscente al Prof. Adis Pasi ed ai suoi collaboratori per l'impegno profuso nella ricerca e per aver sapientemente definito i confini fra la documentazione storica e i "si dice".
Un lavoro serio e qualificato che ci offre la chiave di lettura delle nostre origini, radicate nelle fondamenta di quella Chiesa. Per capire meglio le tappe del nostro viaggio. Per definire meglio le immagini della nostra identità.
>>>Angelo Antonellini Assessore alla Cultura


##Introduzione
##Prefazione
##Cronotassi dei vescovi di Faenza
##Cronotassi dei Rettori (Parroci), economi spirituali e arcipreti di S. Maria delle Grazie in Alfonsine
##Dove Romagna s'inabissa e perde
##Diario di guerra
##Due vite umili - Il dotto Vescovo e il candido frate. Ricordo di Mons. Gardini vescovo di Bertinoro
##Nostra gente. Padre Alfonso da Alfonsine
##... E io ti sparo contro un sonetto
##Canti popolari religiosi in Romagna

